server:
  port: ${base-port:8081}
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  undertow:
    io-threads: 8
    worker-threads: 64
    direct-buffers: true

spring:
  main:
    lazy-initialization: false
    banner-mode: off
  application:
    name: jinkang
  aop:
    proxy-target-class: true

# MySQL数据库配置
  datasource:
    name: localhost
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/graduation_design?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000

# Redis配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-idle: 128
        max-active: 512
        max-wait: 10000
        min-idle: 4



logging:
  level:
    root: ${root-logging-level:INFO}
    org.mybatis: ${mybatis-logging-level:warn}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{SOFA-TraceId},%X{SOFA-SpanId}] [%X{account:-system}] %-5level %logger{36} - %msg%n"
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
